name: pokemon_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  injectable: ^1.5.3
  auto_route: ^5.0.2
  flag: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  injectable_generator: ^1.5.4
  auto_route_generator: ^5.0.2

flutter:
  uses-material-design: true
